/**
 * Zweisprachiges Hintergrund-Bibliotheks-Schema — analog zu Spezies
 * (`species.ts`): ein Kopf plus eine Liste zweisprachiger Unter-Einträge.
 *
 * Ein dünner Adapter über das Open5e-**v2**-Format (`/v2/backgrounds/{key}`).
 * Die Vorteile (`benefits`) tragen — wie die Spezies-Merkmale — je einen
 * englischen (`name`/`desc`) und einen optionalen deutschen (`nameDe`/`descDe`)
 * Wert; das Deutsche wird per LLM-Übersetzung nachgefüllt.
 *
 * `abilityScores` und `featKey` sind bewusst redundant zu den entsprechenden
 * `benefits`-Einträgen: die Liste ist die Anzeige- und Übersetzungsebene, die
 * beiden Felder sind die maschinell nutzbare Mechanik (Attributssteigerungen und
 * der Link auf das Herkunftstalent in `vault/feats`).
 */
//#region schema-overview (auto-generated by `npm run schema:overview` — do not edit)
// ┌─ SCHEMA OVERVIEW
// │ benefitSchema
// │   key? : string = ""
// │   type? : enum("ability_score"|"skill_proficiency"|"tool_proficiency"|"feat"|"equipment"|"other") = "other"  — Art des Vorteils (Open5e-Vokabular).
// │   name : string
// │   nameDe? : string
// │   desc? : string = ""
// │   descDe? : string
// │
// │ backgroundSchema
// │   key : string
// │   source? : enum("srd-2024"|"phb-2024"|"homebrew-sam") = "homebrew-sam"  — Herkunft: SRD 5.2, PHB 2024 oder eigenes Material.
// │   name : string
// │   nameDe? : string
// │   desc? : string = ""
// │   descDe? : string
// │   abilityScores? : string[] = []  — Englische Attributsnamen, z.B. ["Strength","Dexterity","Constitution"].
// │   featKey? : string = ""  — Bibliotheks-Key des Herkunftstalents, z.B. "srd-2024_savage-attacker".
// │   proficiencyGrant?:
// │     skills?:
// │       fixed? : enum("Acrobatics"|"Animal Handling"|"Arcana"|"Athletics"|"Deception"|"History"|"Insight"|"Intimidation"|"Investigation"|"Medicine"|"Nature"|"Perception"|"Performance"|"Persuasion"|"Religion"|"Sleight of Hand"|"Stealth"|"Survival")[] = []  — Ohne Wahl gewährte Fertigkeiten.
// │       choose? : int = 0  — Wie viele Fertigkeiten frei gewählt werden.
// │       from? : enum("Acrobatics"|"Animal Handling"|"Arcana"|"Athletics"|"Deception"|"History"|"Insight"|"Intimidation"|"Investigation"|"Medicine"|"Nature"|"Perception"|"Performance"|"Persuasion"|"Religion"|"Sleight of Hand"|"Stealth"|"Survival")[] = []  — Auswahlliste; leer = beliebige Fertigkeit.
// │     savingThrows? : enum("Strength"|"Dexterity"|"Constitution"|"Intelligence"|"Wisdom"|"Charisma")[] = []
// │     weapons? : enum("Simple"|"Martial")[] = []
// │     weaponsOther? : string[] = []  — Waffen-Übungen außerhalb der zwei Kategorien, z.B. "Martial weapons that have the Light p…
// │     armor? : enum("Light"|"Medium"|"Heavy"|"Shields")[] = []
// │   document?:
// │     key? : string = ""
// │     gamesystem? : string = ""
// │   benefits?[]:
// │     key? : string = ""
// │     type? : enum("ability_score"|"skill_proficiency"|"tool_proficiency"|"feat"|"equipment"|"other") = "other"  — Art des Vorteils (Open5e-Vokabular).
// │     name : string
// │     nameDe? : string
// │     desc? : string = ""
// │     descDe? : string
// └─
//#endregion schema-overview

import { z } from 'zod';
import { sourceField, proficiencyGrantSchema, emptyProficiencyGrant } from './shared';

/** Vokabular der Vorteils-Arten — entspricht Open5es `benefits[].type`. */
export const BENEFIT_TYPES = [
  'ability_score',
  'skill_proficiency',
  'tool_proficiency',
  'feat',
  'equipment',
  'other',
] as const;

export type BenefitType = (typeof BENEFIT_TYPES)[number];

/** Deutsche Anzeige-Labels der Vorteils-Arten (Reihenfolge = Anzeige-Reihenfolge). */
export const BENEFIT_TYPE_LABELS: Record<BenefitType, string> = {
  ability_score: 'Attributswerte',
  skill_proficiency: 'Fertigkeiten',
  tool_proficiency: 'Werkzeugübung',
  feat: 'Herkunftstalent',
  equipment: 'Ausrüstung',
  other: 'Weiteres',
};

/** Ein einzelner Vorteil eines Hintergrunds; zweisprachig (EN Pflicht, DE optional). */
export const benefitSchema = z.object({
  key: z.string().default(''),
  type: z.enum(BENEFIT_TYPES).default('other').describe('Art des Vorteils (Open5e-Vokabular).'),
  name: z.string(),
  nameDe: z.string().optional(),
  desc: z.string().default(''),
  descDe: z.string().optional(),
});

export const backgroundSchema = z.object({
  key: z.string(),
  source: sourceField(),
  name: z.string(),
  nameDe: z.string().optional(),
  desc: z.string().default(''),
  descDe: z.string().optional(),
  abilityScores: z
    .array(z.string())
    .default([])
    .describe('Englische Attributsnamen, z.B. ["Strength","Dexterity","Constitution"].'),
  featKey: z
    .string()
    .default('')
    .describe('Bibliotheks-Key des Herkunftstalents, z.B. "srd-2024_savage-attacker".'),
  /**
   * Die Fertigkeitsübungen als Mechanik (englische Enum-Werte) — abgeleitet aus dem
   * `skill_proficiency`-Vorteil. Alle 16 SRD-Hintergründe gewähren genau zwei FESTE
   * Fertigkeiten. Dieselbe bewusste Redundanz wie `abilityScores`/`featKey`: die
   * `benefits`-Liste ist die Anzeigeebene, dies hier die maschinell nutzbare Form.
   * Werkzeugübungen bleiben Prosa im Vorteil (Werkzeuge sind kein Vokabular der App).
   */
  proficiencyGrant: proficiencyGrantSchema.default(emptyProficiencyGrant),
  document: z
    .object({ key: z.string().default(''), gamesystem: z.string().default('') })
    .default({ key: '', gamesystem: '' }),
  benefits: z.array(benefitSchema).default([]),
});

export type Benefit = z.infer<typeof benefitSchema>;
export type Background = z.infer<typeof backgroundSchema>;
