/**
 * Zweisprachiges Talent-(Feat-)Bibliotheks-Schema — analog zu Klasse/Spezies.
 *
 * Ein dünner Adapter über das Open5e-**v2**-Format (`/v2/feats/{key}`), zweisprachig
 * (EN Pflicht, DE optional). Kompatibel zum leichten Inline-Wörterbuch
 * (`featsLibrary.ts`), das dieselbe `vault/feats`-Sammlung liest (dort wird `key` als
 * `sourceKey` der Charakter-Referenz genutzt).
 */
//#region schema-overview (auto-generated by `npm run schema:overview` — do not edit)
// ┌─ SCHEMA OVERVIEW
// │ featSchema
// │   key? : string = ""
// │   source? : enum("srd-2024"|"phb-2024"|"homebrew-sam") = "homebrew-sam"  — Herkunft: SRD 5.2, PHB 2024 oder eigenes Material.
// │   name : string
// │   nameDe? : string
// │   prerequisite? : string = ""
// │   prerequisiteDe? : string
// │   desc? : string = ""
// │   descDe? : string
// │   proficiencyGrant?:
// │     skills?:
// │       fixed? : enum("Acrobatics"|"Animal Handling"|"Arcana"|"Athletics"|"Deception"|"History"|"Insight"|"Intimidation"|"Investigation"|"Medicine"|"Nature"|"Perception"|"Performance"|"Persuasion"|"Religion"|"Sleight of Hand"|"Stealth"|"Survival")[] = []  — Ohne Wahl gewährte Fertigkeiten.
// │       choose? : int = 0  — Wie viele Fertigkeiten frei gewählt werden.
// │       from? : enum("Acrobatics"|"Animal Handling"|"Arcana"|"Athletics"|"Deception"|"History"|"Insight"|"Intimidation"|"Investigation"|"Medicine"|"Nature"|"Perception"|"Performance"|"Persuasion"|"Religion"|"Sleight of Hand"|"Stealth"|"Survival")[] = []  — Auswahlliste; leer = beliebige Fertigkeit.
// │     savingThrows? : enum("Strength"|"Dexterity"|"Constitution"|"Intelligence"|"Wisdom"|"Charisma")[] = []
// │     weapons? : enum("Simple"|"Martial")[] = []
// │     weaponsOther? : string[] = []  — Waffen-Übungen außerhalb der zwei Kategorien, z.B. "Martial weapons that have the Light p…
// │     armor? : enum("Light"|"Medium"|"Heavy"|"Shields")[] = []
// │   document?:
// │     key? : string = ""
// │     gamesystem? : string = ""
// └─
//#endregion schema-overview

import { z } from 'zod';
import { sourceField, proficiencyGrantSchema, emptyProficiencyGrant } from './shared';

export const featSchema = z.object({
  key: z.string().default(''),
  source: sourceField(),
  name: z.string(),
  nameDe: z.string().optional(),
  prerequisite: z.string().default(''),
  prerequisiteDe: z.string().optional(),
  desc: z.string().default(''),
  descDe: z.string().optional(),
  /**
   * Übungen, die das Talent gewährt (englische Enum-Werte). Im SRD 5.2 betrifft das
   * nur `srd-2024_skilled`. Dessen „any combination of three skills or tools" ist
   * bewusst als `{choose: 3, from: []}` abgebildet — dass auch WERKZEUGE zulässig
   * sind, kann `skillGrant` nicht ausdrücken und bleibt der Prosa überlassen.
   */
  proficiencyGrant: proficiencyGrantSchema.default(emptyProficiencyGrant),
  document: z
    .object({ key: z.string().default(''), gamesystem: z.string().default('') })
    .default({ key: '', gamesystem: '' }),
});

export type Feat = z.infer<typeof featSchema>;
