/**
 * Zweisprachiges Talent-(Feat-)Bibliotheks-Schema — analog zu Klasse/Spezies.
 *
 * Ein dünner Adapter über das Open5e-**v2**-Format (`/v2/feats/{key}`), zweisprachig
 * (EN Pflicht, DE optional). Kompatibel zum leichten Inline-Wörterbuch
 * (`featsLibrary.ts`), das dieselbe `vault/feats`-Sammlung liest (dort wird `key` als
 * `sourceKey` der Charakter-Referenz genutzt).
 */
//#region schema-overview (auto-generated by `npm run schema:overview` — do not edit)
// ┌─ SCHEMA OVERVIEW
// │ featSchema
// │   key? : string = ""
// │   source? : enum("srd-2024"|"phb-2024"|"homebrew-sam") = "homebrew-sam"  — Herkunft: SRD 5.2, PHB 2024 oder eigenes Material.
// │   name : string
// │   nameDe? : string
// │   prerequisite? : string = ""
// │   prerequisiteDe? : string
// │   desc? : string = ""
// │   descDe? : string
// │   document?:
// │     key? : string = ""
// │     gamesystem? : string = ""
// └─
//#endregion schema-overview

import { z } from 'zod';
import { sourceField } from './shared';

export const featSchema = z.object({
  key: z.string().default(''),
  source: sourceField(),
  name: z.string(),
  nameDe: z.string().optional(),
  prerequisite: z.string().default(''),
  prerequisiteDe: z.string().optional(),
  desc: z.string().default(''),
  descDe: z.string().optional(),
  document: z
    .object({ key: z.string().default(''), gamesystem: z.string().default('') })
    .default({ key: '', gamesystem: '' }),
});

export type Feat = z.infer<typeof featSchema>;
