/**
 * Zweisprachiges Spezies-Bibliotheks-Schema — analog zur Klassen-Progression
 * (`classProgression.ts`), aber ohne Stufen-Konzept.
 *
 * Ein dünner Adapter über das Open5e-**v2**-Format (`/v2/species/{key}`): die
 * Merkmale (`traits`) tragen — wie bei Zaubern/Gegenständen — je einen englischen
 * (`name`/`desc`) und einen optionalen deutschen (`nameDe`/`descDe`) Wert. Das
 * Deutsche wird per LLM-Übersetzung nachgefüllt; Open5e liefert nur Englisch.
 */
//#region schema-overview (auto-generated by `npm run schema:overview` — do not edit)
// ┌─ SCHEMA OVERVIEW
// │ traitSchema
// │   key? : string = ""
// │   name : string
// │   nameDe? : string
// │   desc? : string = ""
// │   descDe? : string
// │   proficiencyGrant?:
// │     skills?:
// │       fixed? : enum("Acrobatics"|"Animal Handling"|"Arcana"|"Athletics"|"Deception"|"History"|"Insight"|"Intimidation"|"Investigation"|"Medicine"|"Nature"|"Perception"|"Performance"|"Persuasion"|"Religion"|"Sleight of Hand"|"Stealth"|"Survival")[] = []  — Ohne Wahl gewährte Fertigkeiten.
// │       choose? : int = 0  — Wie viele Fertigkeiten frei gewählt werden.
// │       from? : enum("Acrobatics"|"Animal Handling"|"Arcana"|"Athletics"|"Deception"|"History"|"Insight"|"Intimidation"|"Investigation"|"Medicine"|"Nature"|"Perception"|"Performance"|"Persuasion"|"Religion"|"Sleight of Hand"|"Stealth"|"Survival")[] = []  — Auswahlliste; leer = beliebige Fertigkeit.
// │     savingThrows? : enum("Strength"|"Dexterity"|"Constitution"|"Intelligence"|"Wisdom"|"Charisma")[] = []
// │     weapons? : enum("Simple"|"Martial")[] = []
// │     weaponsOther? : string[] = []  — Waffen-Übungen außerhalb der zwei Kategorien, z.B. "Martial weapons that have the Light p…
// │     armor? : enum("Light"|"Medium"|"Heavy"|"Shields")[] = []
// │
// │ speciesSchema
// │   key : string
// │   source? : enum("srd-2024"|"phb-2024"|"homebrew-sam") = "homebrew-sam"  — Herkunft: SRD 5.2, PHB 2024 oder eigenes Material.
// │   name : string
// │   nameDe? : string
// │   size? : string = ""
// │   speed? : string = ""
// │   document?:
// │     key? : string = ""
// │     gamesystem? : string = ""
// │   traits?[]:
// │     key? : string = ""
// │     name : string
// │     nameDe? : string
// │     desc? : string = ""
// │     descDe? : string
// │     proficiencyGrant?:
// │       skills?:
// │         fixed? : enum("Acrobatics"|"Animal Handling"|"Arcana"|"Athletics"|"Deception"|"History"|"Insight"|"Intimidation"|"Investigation"|"Medicine"|"Nature"|"Perception"|"Performance"|"Persuasion"|"Religion"|"Sleight of Hand"|"Stealth"|"Survival")[] = []  — Ohne Wahl gewährte Fertigkeiten.
// │         choose? : int = 0  — Wie viele Fertigkeiten frei gewählt werden.
// │         from? : enum("Acrobatics"|"Animal Handling"|"Arcana"|"Athletics"|"Deception"|"History"|"Insight"|"Intimidation"|"Investigation"|"Medicine"|"Nature"|"Perception"|"Performance"|"Persuasion"|"Religion"|"Sleight of Hand"|"Stealth"|"Survival")[] = []  — Auswahlliste; leer = beliebige Fertigkeit.
// │       savingThrows? : enum("Strength"|"Dexterity"|"Constitution"|"Intelligence"|"Wisdom"|"Charisma")[] = []
// │       weapons? : enum("Simple"|"Martial")[] = []
// │       weaponsOther? : string[] = []  — Waffen-Übungen außerhalb der zwei Kategorien, z.B. "Martial weapons that have the Light p…
// │       armor? : enum("Light"|"Medium"|"Heavy"|"Shields")[] = []
// └─
//#endregion schema-overview

import { z } from 'zod';
import { sourceField, proficiencyGrantSchema, emptyProficiencyGrant } from './shared';

/**
 * Ein Speziesmerkmal (Trait); zweisprachig (EN Pflicht, DE optional).
 *
 * Der Grant hängt am MERKMAL, nicht an der Spezies: im SRD 5.2 gewähren nur zwei
 * Merkmale eine Fertigkeit (Elf „Keen Senses", Mensch „Skillful"), und beide sind
 * eine Wahl. Für alles Übrige bleibt er leer.
 */
export const traitSchema = z.object({
  key: z.string().default(''),
  name: z.string(),
  nameDe: z.string().optional(),
  desc: z.string().default(''),
  descDe: z.string().optional(),
  proficiencyGrant: proficiencyGrantSchema.default(emptyProficiencyGrant),
});

export const speciesSchema = z.object({
  key: z.string(),
  source: sourceField(),
  name: z.string(),
  nameDe: z.string().optional(),
  size: z.string().default(''),
  speed: z.string().default(''),
  document: z
    .object({ key: z.string().default(''), gamesystem: z.string().default('') })
    .default({ key: '', gamesystem: '' }),
  traits: z.array(traitSchema).default([]),
});

export type Trait = z.infer<typeof traitSchema>;
export type Species = z.infer<typeof speciesSchema>;
