/**
 * Single Source of Truth für Zauber: Zod-Schema → TS-Type + Runtime-Validator +
 * LLM-JSON-Schema (siehe shared.ts). Label-Maps/Helper bleiben in types.ts.
 */
//#region schema-overview (auto-generated by `npm run schema:overview` — do not edit)
// ┌─ SCHEMA OVERVIEW
// │ spellSchema
// │   index? : string  — API-Slug (leer bei Homebrew).
// │   key? : string  — Open5e-Key, z.B. "srd-2024_moonbeam" (für Verlinkung/Dedup, leer bei Homebrew).
// │   name : string
// │   name_en? : string  — Kanonischer englischer SRD-Name (für EN↔DE-Matching, z.B. wenn die KI "Moonbeam" liefert …
// │   level? : int = 0  — 0 = Zaubertrick, 1–9
// │   school? : enum("abjuration"|"conjuration"|"divination"|"enchantment"|"evocation"|"illusion"|"necromancy"|"transmutation") = "evocation"  — engl. Schule: abjuration, conjuration, divination, enchantment, evocation, illusion, necr…
// │   casting_time? : string = ""
// │   range? : string = ""
// │   components?:
// │     verbal? : bool = false
// │     somatic? : bool = false
// │     material? : bool = false
// │     materials_needed? : string | null = null
// │   duration? : string = ""
// │   concentration? : bool = false
// │   ritual? : bool = false
// │   classes? : string[] = []
// │   desc? : string[] = []  — Beschreibung (Absätze).
// │   desc_de? : string[]  — Deutsche Beschreibung.
// │   higher_level? : string[] | null
// │   higher_level_de? : string[] | null
// │   damage?:
// │     damage_type:
// │       index : string
// │       name : string
// │     damage_at_slot_level? : {…}
// │     damage_at_character_level? : {…}
// │   dc?:
// │     dc_type:
// │       index : string
// │       name : string
// │     dc_success : string  — 'half' | 'none' | 'other'
// │   area_of_effect?:
// │     type : string  — 'sphere' | 'cone' | 'cube' | 'line' | 'cylinder'
// │     size : number  — in Fuß
// │   source? : enum("srd-2024"|"phb-2024"|"homebrew-sam") = "homebrew-sam"  — Herkunft: SRD 5.2, PHB 2024 oder eigenes Material.
// └─
//#endregion schema-overview

import { z } from 'zod';
import { SPELL_SCHOOLS, type SpellSchool } from '../types';
import { namedRef, sourceField, migrateSourceLegacy } from './shared';

const schoolEnum = z.enum(Object.keys(SPELL_SCHOOLS) as [SpellSchool, ...SpellSchool[]]);

export const spellSchema = z.object({
  index: z.string().optional().describe('API-Slug (leer bei Homebrew).'),
  key: z.string().optional().describe('Open5e-Key, z.B. "srd-2024_moonbeam" (für Verlinkung/Dedup; bei Zaubern meist leer).'),
  name: z.string(),
  name_en: z.string().optional().describe('Kanonischer englischer SRD-Name (für EN↔DE-Matching, z.B. wenn die KI "Moonbeam" liefert und der Zauber lokal als "Mondstrahl" liegt).'),
  level: z.number().int().default(0).describe('0 = Zaubertrick, 1–9'),
  school: schoolEnum
    .default('evocation')
    .describe('engl. Schule: abjuration, conjuration, divination, enchantment, evocation, illusion, necromancy, transmutation'),
  casting_time: z.string().default(''),
  range: z.string().default(''),
  components: z
    .object({
      verbal: z.boolean().default(false),
      somatic: z.boolean().default(false),
      material: z.boolean().default(false),
      materials_needed: z.string().nullable().default(null),
    })
    .default({ verbal: false, somatic: false, material: false, materials_needed: null }),
  duration: z.string().default(''),
  concentration: z.boolean().default(false),
  ritual: z.boolean().default(false),
  classes: z.array(z.string()).default([]),
  desc: z.array(z.string()).default([]).describe('Beschreibung (Absätze).'),
  desc_de: z.array(z.string()).optional().describe('Deutsche Beschreibung.'),
  higher_level: z.array(z.string()).nullable().optional(),
  higher_level_de: z.array(z.string()).nullable().optional(),
  damage: z
    .object({
      damage_type: namedRef(),
      damage_at_slot_level: z.record(z.string(), z.string()).optional(),
      damage_at_character_level: z.record(z.string(), z.string()).optional(),
    })
    .optional(),
  dc: z
    .object({
      dc_type: namedRef(),
      dc_success: z.string().describe("'half' | 'none' | 'other'"),
    })
    .optional(),
  area_of_effect: z
    .object({
      type: z.string().describe("'sphere' | 'cone' | 'cube' | 'line' | 'cylinder'"),
      size: z.number().describe('in Fuß'),
    })
    .optional(),
  source: sourceField(),
});

export type Spell = z.infer<typeof spellSchema>;
export type SpellDamage = NonNullable<z.infer<typeof spellSchema>['damage']>;

/** Migriert Altformat-Felder, bevor das Schema greift. Idempotent. */
export function migrateSpellLegacy(raw: unknown): Record<string, unknown> {
  if (!raw || typeof raw !== 'object') return {};
  const s = { ...(raw as Record<string, unknown>) };

  // level: string → number
  if (typeof s.level === 'string') {
    s.level = s.level === 'cantrip' || s.level === '0' ? 0 : parseInt(s.level, 10) || 0;
  }
  // description (alt) → desc_de
  if (typeof s.description === 'string') {
    s.desc_de ??= [s.description];
    delete s.description;
  }
  // higher_levels (alt) → higher_level_de
  if ('higher_levels' in s) {
    const hl = s.higher_levels as string | null;
    if (hl) s.higher_level_de ??= [hl];
    delete s.higher_levels;
  }
  return migrateSourceLegacy(s);
}
